# Generated by Django 5.0 on 2023-12-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_profile_bio_gift_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gift',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='store',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
